# The new, script-based netlify.toml

[build]
  # The ONLY command Netlify will run. It runs our custom script from the root.
  command = "./build-script.sh"
  
  # The final, published site is now the 'dist' folder inside 'frontend'
  publish = "frontend/dist"

# We no longer need a [functions] block because we are manually placing them
# in the publish directory, which is a special location Netlify always checks.
# Netlify will automatically discover functions placed inside the publish directory.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200