[build]
  command = "npm run build"
  publish = "dist" # Vite will create this folder at the root

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200