# The final, prefix-based netlify.toml

[build]
  # The command is now run from the root, but targets the frontend folder
  command = "npm run build --prefix frontend"
  
  # The final website is still in the 'frontend/dist' folder
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200