# This is the FINAL, corrected netlify.toml

# The [build] settings are for your FRONTEND
[build]
  # "Start all build operations inside this folder"
  base = "frontend"
  
  # "Run this command (npm install, then vite build)"
  command = "npm run build"
  
  # "The final website is in the 'dist' folder, which is INSIDE the 'base' directory"
  publish = "dist"

# The [functions] settings are relative to the ROOT of the repository
[functions]
  # "My functions are in a top-level folder called 'netlify/functions'"
  directory = "netlify/functions"

# The redirect rule remains the same
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200