# File: netlify.toml - CORRECTED VERSION

# This section defines your build process
[build]
# Base directory: where to run the build command from
  base = "frontend/"
  command = "npm run build"
  publish = "dist/"
  
# This is the correct way to define the directory for ALL functions.
# Netlify will automatically look for .js files inside this folder.
# This is simpler and less error-prone than declaring each one.
[functions]
  directory = "netlify/functions"

  external_node_modules = ["node-fetch"]

# This is a helpful rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200