# Final, corrected netlify.toml for a root package.json

[build]
  # The publish directory is still the frontend's dist folder
  publish = "frontend/dist"
  
  # The command to run from the root directory
  command = "npm install && cd frontend && npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200