# This is the definitive netlify.toml for your project structure

# The [build] settings tell Netlify what to do for your FRONTEND
[build]
  # "Start in the 'frontend' folder"
  base = "frontend"
  
  # "Inside the 'frontend' folder, run this command"
  command = "npm run build"
  
  # "After the build, the final website is in the 'frontend/dist' folder"
  publish = "frontend/dist"

# The [functions] settings tell Netlify about your BACKEND
[functions]
  # "The functions are in a folder named 'netlify/functions' at the project root"
  directory = "netlify/functions"

# The redirect rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200